---
fixtures:
  repositories:
    augeasproviders_core: https://github.com/voxpupuli/puppet-augeasproviders_core.git
    augeasproviders_sysctl: https://github.com/voxpupuli/puppet-augeasproviders_sysctl.git
    mount_core: https://github.com/puppetlabs/puppetlabs-mount_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
