---
spec/spec_helper.rb:
  hiera_config: "'spec/fixtures/hiera/hiera.yaml'"
  mock_with: ':mocha'

spec/spec_helper_acceptance.rb:
  unmanaged: false

# Minimum size that mkswap will accept is 40MB.
.github/workflows/ci.yml:
  beaker_hypervisor: vagrant_libvirt
  beaker_facter: 'memory.system.total:TotalMemory:100 MiB'
